version: "3.7"

services:
  iac_worker:
    build: outpost-py
    image: outpost-worker
    environment:
      - DOCKER_HOST=dockerd.outpost:2375
      - REGISTRY_HOST=registry.outpost
      - GIT_HOST=file:///srv/git
      - GATEWAY_REQUEST=redis://gateway.outpost/0
      - GATEWAY_RESPONSE=redis://gateway.outpost/1
      - GODEBUG=x509ignoreCN=0
      - TERRAFORM_DIR=/var/terraform
    volumes:
      - iac_terraform:/var/terraform
      - iac_git:/srv/git
    depends_on:
      - iac_dockerd
      - iac_registry
      - gateway_messages
  
  iac_dockerd:
    image: docker:dind
    restart: always
    hostname: dockerd.outpost
    privileged: true
    ports:
      - 8080:8000
    environment:
      - DOCKER_TLS_CERTDIR=  # Disable TLS
    volumes:
      - ./dockerd/daemon.json:/etc/docker/daemon.json
      - iac_dockerd:/var/lib/docker
  
  iac_registry:
    image: registry
    restart: always
    hostname: registry.outpost
    volumes:
      - iac_registry:/var/lib/registry
      - ./certificates/:/certs/:ro
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.fullchain.pem
      - REGISTRY_HTTP_TLS_KEY=/certs/registry.privkey.pem
    networks:
      - default
      - gateway
  
  iac_dashboard:
    build: dashboard
    image: outpost-dashboard
    restart: always
    ports:
      - 8880:8080
    environment:
      - REGISTRY_HOST=registry.outpost
      - REGISTRY_VERIFY_SSL=false
      - DOCKER_HOST=dockerd.outpost:2375
    depends_on:
      - iac_registry
  
  gateway_messages:
    image: redis:alpine
    restart: always
    hostname: gateway.outpost
    volumes:
      - gateway_messages:/data
    networks:
      - gateway
      - default
  
  gateway_dashboard:
    build: queue-ui
    image: outpost-queue-ui
    restart: always
    command: --broker=redis://gateway.outpost/0 --persistent --db=/var/dashboard/tasks.db
    ports:
      - 5556:5555
    volumes:
      - gateway_dashboard:/var/dashboard
    networks:
      - gateway
    depends_on:
      - gateway_messages
  
  gateway_dockerd:
    image: docker:dind
    restart: always
    hostname: gateway-dockerd.outpost
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=  # Disable TLS
    volumes:
      - ./dockerd/daemon.json:/etc/docker/daemon.json
      - gateway_dockerd:/var/lib/docker
    networks:
      - gateway
  
  gateway_worker:
    build: outpost-py
    image: outpost-worker
    restart: always
    command: celery --app=gateway worker --loglevel=info
    environment:
      - DOCKER_HOST=gateway-dockerd.outpost:2375
      - REGISTRY_HOST=registry.outpost
      - GIT_HOST=file:///srv/git
      - GATEWAY_REQUEST=redis://gateway.outpost/0
      - GATEWAY_RESPONSE=redis://gateway.outpost/1
      - TXRX_REQUEST=redis://txrx.outpost/0
      - TXRX_RESPONSE=redis://txrx.outpost/1
      - TXRX_DELAY=$TXRX_DELAY
      - RX_DATA=/usr/rx
    volumes:
      - iac_git:/srv/git
      - txrx_data:/usr/rx
    networks:
      - gateway
    depends_on:
      - txrx_messages
      - gateway_messages
      - gateway_dockerd
  
  txrx_messages:
    image: redis:alpine
    restart: always
    hostname: txrx.outpost
    volumes:
      - txrx_messages:/data
    networks:
      - txrx
      - gateway
  
  txrx_dashboard:
    build: queue-ui
    image: outpost-queue-ui
    restart: always
    command: --broker=redis://txrx.outpost/0 --persistent=true --db=/var/dashboard/tasks.db
    ports:
      - 5555:5555
    volumes:
      - txrx_dashboard:/var/dashboard
    networks:
      - txrx
    depends_on:
      - txrx_messages
  
  txrx_dockerd:
    image: docker:dind
    restart: always
    hostname: txrx-dockerd.outpost
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=  # Disable TLS
    volumes:
      - txrx_dockerd:/var/lib/docker
    networks:
      - txrx
  
  txrx_worker:
    build: outpost-py
    image: outpost-worker
    restart: always
    command: celery --app=txrx worker --loglevel=info
    environment:
      - DOCKER_HOST=txrx-dockerd.outpost:2375
      - DOCKER_BUILD_DIR=/var/build/target
      - TERRAFORM_TEMPLATE_PATH=/src/terraform
      - TXRX_REQUEST=redis://txrx.outpost/0
      - TXRX_RESPONSE=redis://txrx.outpost/1
      - TXRX_DELAY=$TXRX_DELAY
      - RX_DATA=/tmp
    volumes:
      - txrx_data:/tmp
      - txrx_git:/var/git
      - ./terraform:/src/terraform
      - ./target-py:/var/build/target
    networks:
      - txrx
    depends_on:
      - txrx_messages
      - txrx_dockerd

volumes:
  iac_dockerd:
  iac_registry:
  iac_git:
  iac_terraform:
  gateway_messages:
  gateway_dashboard:
  gateway_dockerd:
  txrx_messages:
  txrx_dashboard:
  txrx_dockerd:
  txrx_data:
  txrx_git:

networks:
  default:
  gateway:
  txrx:


