version: "3.7"

services:
  python:
    build: python
    image: outpost-python
    environment:
      - DOCKER_HOST=dockerd.outpost:2375
    depends_on:
      - dockerd
  
  registry:
    image: registry
    restart: always
    hostname: "registry.outpost"
    ports:
      - 80:80
    volumes:
      - registry:/var/lib/registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:80
  
  dockerd:
    image: docker:dind
    restart: always
    privileged: true
    hostname: "dockerd.outpost"
    ports:
      - 2376:2375
    volumes:
      - ./dockerd/daemon.json:/etc/docker/daemon.json
      - dockerd:/var/lib/docker
    environment:
      - DOCKER_TLS_CERTDIR=  # Disable TLS

volumes:
  registry:
  dockerd:

