version: "3.7"

services:
  client:
    build: client
    image: outpost-client
    environment:
      - DOCKER_HOST=dockerd.outpost:2375
      - REGISTRY_HOST=registry.outpost
      - GATEWAY_REQUEST=redis://gateway.outpost:6379/0
      - GATEWAY_RESPONSE=redis://gateway.outpost:6379/1
    volumes:
      - ./client/version_number.txt:/usr/src/app/version_number.txt
    depends_on:
      - dockerd
      - gateway_messages
  
  registry:
    image: registry
    restart: always
    hostname: registry.outpost
    volumes:
      - registry:/var/lib/registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:80
    networks:
      - default
      - gateway
  
  registry_ui:
    image: parabuzzle/craneoperator:latest
    restart: always
    ports:
      - 8000:80
    environment:
      - REGISTRY_HOST=registry.outpost
      - REGISTRY_PORT=80
      - REGISTRY_PROTOCOL=http
    depends_on:
      - registry
  
  dockerd:
    image: docker:dind
    restart: always
    hostname: dockerd.outpost
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=  # Disable TLS
    volumes:
      - ./dockerd/daemon.json:/etc/docker/daemon.json
      - dockerd:/var/lib/docker
  
  gateway_messages:
    image: redis:5-alpine
    restart: always
    hostname: gateway.outpost
    volumes:
      - gateway_messages:/data
    networks:
      - gateway
      - default
  
  gateway_dashboard:
    build: queue_ui
    image: outpost-queue-ui
    restart: always
    command: --broker=redis://gateway.outpost:6379/0
    ports:
      - 5556:5555
    networks:
      - gateway
    depends_on:
      - gateway_messages
  
  gateway_dockerd:
    image: docker:dind
    restart: always
    hostname: gateway-dockerd.outpost
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=  # Disable TLS
    volumes:
      - gateway_dockerd:/var/lib/docker
      - ./dockerd/daemon.json:/etc/docker/daemon.json
    networks:
      - gateway
  
  gateway_worker:
    build: client
    image: outpost-worker
    restart: always
    command: celery --app=gateway worker --loglevel=info
    environment:
      - DOCKER_HOST=gateway-dockerd.outpost:2375
      - REGISTRY_HOST=registry.outpost
      - GATEWAY_REQUEST=redis://gateway.outpost:6379/0
      - GATEWAY_RESPONSE=redis://gateway.outpost:6379/1
      - TXRX_REQUEST=redis://txrx.outpost:6379/0
      - TXRX_RESPONSE=redis://txrx.outpost:6379/1
      - RX_DATA=/usr/rx
    volumes:
      - txrx_data:/usr/rx
    networks:
      - gateway
    depends_on:
      - txrx_messages
      - gateway_messages
      - gateway_dockerd
  
  txrx_messages:
    image: redis:5-alpine
    restart: always
    hostname: txrx.outpost
    volumes:
      - txrx_messages:/data
    networks:
      - txrx
      - gateway
  
  txrx_dashboard:
    build: queue_ui
    image: outpost-queue-ui
    restart: always
    command: --broker=redis://txrx.outpost:6379/0
    ports:
      - 5555:5555
    networks:
      - txrx
    depends_on:
      - txrx_messages
  
  txrx_dockerd:
    image: docker:dind
    restart: always
    hostname: txrx-dockerd.outpost
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=  # Disable TLS
    volumes:
      - txrx_dockerd:/var/lib/docker
    networks:
      - txrx
  
  txrx_worker:
    build: client
    image: outpost-worker
    restart: always
    command: celery --app=txrx worker --loglevel=info
    environment:
      - DOCKER_HOST=txrx-dockerd.outpost:2375
      - TXRX_REQUEST=redis://txrx.outpost:6379/0
      - TXRX_RESPONSE=redis://txrx.outpost:6379/1
      - RX_DATA=/tmp
    volumes:
      - txrx_data:/tmp
    networks:
      - txrx
    depends_on:
      - txrx_messages
      - txrx_dockerd

volumes:
  registry:
  dockerd:
  gateway_messages:
  gateway_dockerd:
  txrx_messages:
  txrx_dockerd:
  txrx_data:

networks:
  default:
  gateway:
  txrx:


