version: "3.7"

services:
  client:
    build: client
    image: outpost-client
    environment:
      - TXRX_QUEUE=redis://queues:6379/0
      - TXRX_RESULTS=redis://queues:6379/1
      - DOCKER_HOST=dockerd.outpost:2375
      - REGISTRY_HOST=registry.outpost
      - RX_DATA=/tmp
    volumes:
      - rx_data:/tmp
      - ./client/version_number.txt:/usr/src/app/version_number.txt
    depends_on:
      - dockerd
      - queues
  
  worker:
    build: client
    image: outpost-worker
    command: celery --app=txrx worker --loglevel=info
    environment:
      - TXRX_QUEUE=redis://queues:6379/0
      - TXRX_RESULTS=redis://queues:6379/1
      - DOCKER_HOST=dockerd.outpost:2375
      - REGISTRY_HOST=registry.outpost
      - RX_DATA=/tmp
    volumes:
      - rx_data:/tmp
    depends_on:
      - dockerd
      - queues
  
  registry:
    image: registry
    restart: always
    hostname: registry.outpost
    volumes:
      - registry:/var/lib/registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:80
  
  registry_ui:
    image: parabuzzle/craneoperator:latest
    restart: always
    ports:
      - 8000:80
    environment:
      - REGISTRY_HOST=registry.outpost
      - REGISTRY_PORT=80
      - REGISTRY_PROTOCOL=http
    depends_on:
      - registry
  
  dockerd:
    image: docker:dind
    restart: always
    privileged: true
    hostname: dockerd.outpost
    volumes:
      - ./dockerd/daemon.json:/etc/docker/daemon.json
      - dockerd:/var/lib/docker
    environment:
      - DOCKER_TLS_CERTDIR=  # Disable TLS
  
  queues:
    image: redis:5-alpine
    volumes:
      - queues:/data
  
  queue_ui:
    build: queue_ui
    image: outpost-queue-ui
    command: --broker=redis://queues:6379/0
    ports:
      - 5555:5555
    depends_on:
      - queues

volumes:
  registry:
  dockerd:
  rx_data:
  queues:

