version: "3.7"

services:
  registry:
    image: registry
    restart: always
    hostname: "registry.outpost"
    ports:
      - 80:80
    volumes:
      - registry:/var/lib/registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:80
  
  dockerd:
    image: docker:dind
    privileged: true
    volumes:
      - ./dockerd/daemon.json:/etc/docker/daemon.json
      - dockerd:/var/lib/docker

volumes:
  registry:
  dockerd:

