version: "3.7"

services:
  registry:
    image: registry
    restart: always
    ports:
      - 80:80
    volumes:
      - registry:/var/lib/registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:80

volumes:
  registry:

