name: Validate Outpost python

on: push

jobs:
  validate-outpost-py:
    name: Validate main Outpost application
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Linting
        run: |
          cd outpost-py
          python -m pip install --upgrade pip
          python -m pip install -r requirements_linting.txt
          flake8
  
  validate-registry-ui:
    name: Validate Dashboard application
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Linting
        run: |
          cd dashboard
          python -m pip install --upgrade pip
          python -m pip install -r requirements_linting.txt
          flake8
      - name: Typing
        run: |
          cd dashboard
          python -m pip install --upgrade pip
          python -m pip install -r requirements_typing.txt
          mypy
      - name: Testing
        run: |
          cd dashboard
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m unittest

